---
- name: config new subdomain script for ddns update task scheduler
  hosts: all
  become: true
  gather_facts: true
   
  tasks:
  
  - name: add new A record
    include_role:
      - roles/add_record
    when: add_record|bool
  
  - name: add new ddns update script
    include_role:
      - ddns_update
